services:
  shiny-app:
    build: .
    ports:
      - "3838:3838"
    volumes:
      # Mount volumes for persistent storage of uploaded files
      - ./uploads:/srv/shiny-server/uploads
      - ./uploaded_files:/srv/shiny-server/uploaded_files
      - ./www:/srv/shiny-server/www
      # Mount logs for debugging
      - ./logs:/var/log/shiny-server
    environment:
      - SHINY_LOG_STDERR=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3838"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
